name: qna
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - fastapi
  - uvicorn
  - python-multipart
  - pillow
  - yaml
  - aiofiles
  - tensorflow
  - transformers
  - protobuf
  - pip:
      - torch
      - torchvision
      - kfserving
